name: Test

on:
  push:
    branches:
      - f25
  pull_request:
    branches:
      - f25

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: 'production'

    steps:
      - uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install Python dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest

